### ISSUE TITLE
panic: no process-level CryptoProvider available

### ISSUE THREAD

**Issue by 1zun4** [stalwartlabs/mail-send#35]
```rust
async fn send_email(cfg: &web::Data<Config>, customer_email: &str, amount: f64, secret: &str) -> Result<()> {
    let now = Utc::now();

    let mail_content = fs::read_to_string("mail.html").await?
        .replace("%donated_amount%", &*format!("{:.2}", amount))
        .replace("%secret%", &secret)
        .replace("%time%", &now.to_rfc2822());

    let message = MessageBuilder::new()
        .from(("Service", &*cfg.mail.from))
        .to((customer_email, customer_email))
        .subject(&cfg.mail.subject)
        .html_body(&mail_content);

    SmtpClientBuilder::new(&cfg.mail.smtp.host, cfg.mail.smtp.port)
        .implicit_tls(false)
        .credentials(Credentials::new(&cfg.mail.smtp.username, &cfg.mail.smtp.password))
        .connect()
        .await?
        .send(message)
        .await?;

    Ok(())
}
``` 

```
thread 'actix-rt|system:0|arbiter:0' panicked at /home/izuna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.12/src/crypto/mod.rs:259:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
stack backtrace:
   0: rust_begin_unwind
             at /rustc/730d5d4095a264ef5f7c0a0781eea68c15431d45/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/730d5d4095a264ef5f7c0a0781eea68c15431d45/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/730d5d4095a264ef5f7c0a0781eea68c15431d45/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/730d5d4095a264ef5f7c0a0781eea68c15431d45/library/core/src/option.rs:2027:5
   4: core::option::Option<T>::expect
             at /rustc/730d5d4095a264ef5f7c0a0781eea68c15431d45/library/core/src/option.rs:930:21
   5: rustls::crypto::CryptoProvider::get_default_or_install_from_crate_features
             at /home/izuna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.12/src/crypto/mod.rs:258:24
   6: rustls::client::client_conn::ClientConfig::builder_with_protocol_versions
             at /home/izuna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.12/src/client/client_conn.rs:294:13
   7: rustls::client::client_conn::ClientConfig::builder
             at /home/izuna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.12/src/client/client_conn.rs:271:9
   8: mail_send::smtp::tls::build_tls_connector
             at /home/izuna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mail-send-0.4.9/src/smtp/tls.rs:90:9
   9: mail_send::smtp::builder::<impl mail_send::SmtpClientBuilder<T>>::new
             at /home/izuna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mail-send-0.4.9/src/smtp/builder.rs:29:28
  10: liquidbounce_api::routes::v2::payment::products::donation::send_email::{{closure}}
             at ./src/routes/v2/payment/products/donation.rs:88:5
```

```
[izuna@izuna-b550aoruseliteaxv2 liquidbounce_api]$ rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.82.0-nightly (730d5d409 2024-08-10)`

```
I have no idea why this happens. It already faults at `new(...)` at `tls_connector: build_tls_connector(false)`.

**Comment by 1zun4** [comment]
I figured it out. I had `rustls` specified in my `cargo.toml` and that conflicted with `mail-send` for some reason.
